### ISSUE TITLE
Also send notification for approved pull requests

### ISSUE THREAD

**Issue by blixgardhn** [blixgardhn/github-teams-notifier#9]
To make sure no approved pull requests are forgotten and remain unmerged there should be a notification to the creator at the time the pull request is approved.

### DOD

When a pull request is approved a notification is sent mentioning the creator of the pull request.

**Comment by blixgardhn** [comment]
This snippet from chatgpt should help

```  
name: Notify Teams on Pull Request Review

on:
  pull_request_review:
    types:
      - submitted

jobs:
  notify_teams:
    runs-on: ubuntu-latest
    steps:
      - name: Extract PR Creator and Review State
        id: pr_details
        run: |
          echo "creator=${{ github.event.pull_request.user.login }}" >> $GITHUB_ENV
          echo "reviewer=${{ github.event.review.user.login }}" >> $GITHUB_ENV
          echo "review_state=${{ github.event.review.state }}" >> $GITHUB_ENV

      - name: Send Teams Notification
        uses: deepakputhraya/ms-teams-webhook-action@v1.3
        with:
          webhook-uri: ${{ secrets.TEAMS_WEBHOOK_URL }}
          message: >
            Pull request #${{ github.event.pull_request.number }} 
            ("${{ github.event.pull_request.title }}") by 
            @${{ env.creator }} has been reviewed by 
            @${{ env.reviewer }} with a status of "${{ env.review_state }}".
```
